### ISSUE TITLE
Incorrect trigger - RCS1083 triggers on Count() values other than zero

### ISSUE THREAD

**Issue by pyrocumulus** [JosefPihrt/Roslynator#259] opened 2018-01-24 10:06 UTC
**Refactoring:**
RCS1083 Call 'Enumerable.Any' instead of 'Enumerable.Count'

**Problem:**
It triggers too easily, leading to potential bugs. It also triggers when the Count is compared to values other than 0. If the replacement for Any() is executed, the code is no longer equivalent. 

**Reproduction code:**
```csharp
            IEnumerable<string> list = new List<string>() { "x", "y" };
            if (list.Count() > 100) // RCS1083 triggers on this line
            {
                
            }
```
Replacing Count() by Any() here would actually check if there is any item at all, instead of more than 100 items.

**Suggested solution:**
Make sure that RCS1083 only triggers when IEnumerable.Count() is compared to 0.

**Version info:**
Visual Studio Professional 2017 v15.5.4
Roslynator 2017 v1.6.30

**Comment by JosefPihrt** [comment] 2018-01-24 13:49
This looks like duplicate of #252.

Your code sample will be tranformed into:
```csharp
IEnumerable<string> list = new List<string>() { "x", "y" };
if (list.Skip(100).Any())
{
}
```

**Comment by pyrocumulus** [comment] 2018-01-24 14:26
Ah, sorry I missed that previous issue! I did check open issues but just not the closed ones, it's duplicate indeed 🤦‍♂️

**Closed** 2018-01-24 14:39 UTC
Labels: Area-Analyzers, Resolution-Duplicate

**Comment by JosefPihrt** [comment] 2018-04-15 11:14
#315
