### ISSUE TITLE
RCS1128 Incorrect fix when code in if refers to variable itself

### ISSUE THREAD

**Issue by MSeifert04** [JosefPihrt/Roslynator#374] opened 2018-05-29 07:57 UTC
Currently RCS1128 is shown for code like this:
```
public void Test(string x)
{
  var a = x;
  if (a != null) a = "," + a + ",";
}
```

However the suggested fix (use coalesce expression) isn't valid:

```
var a = x ?? (string)("," + a + ",");
```

Then the compiler complains (CS0841) `Cannot use local variable 'a' before it is declared`.

Additionally the fix would be wrong here because I check for `!= null`. The fix would be only valid if I checked for `== null`, or am I messing up the boolean logic?

**Comment by JosefPihrt** [comment] 2018-05-29 12:18
A duplicate of https://github.com/JosefPihrt/Roslynator/issues/370

**Closed** 2018-05-29 12:18 UTC
Labels: Area-Analyzers, Bug, Resolution-Duplicate

**Comment by MSeifert04** [comment] 2018-05-29 12:30
Thanks for the fast fix. 👍 

Sorry for the duplicate, I totally missed it when I searched for similar issues.
