### ISSUE TITLE
AD0001	Analyzer 'Roslynator.CSharp.DiagnosticAnalyzers.UseMethodGroupInsteadOfAnonymousFunctionDiagnosticAnalyzer' threw an exception of type 'System.NullReferenceException'

### ISSUE THREAD

**Issue by BuhTig4ever** [JosefPihrt/Roslynator#202] opened 2017-11-08 14:15 UTC
Severity	Code	Description	Project	File	Line	Category	Detail Description
Warning	AD0001	Analyzer 'Roslynator.CSharp.DiagnosticAnalyzers.UseMethodGroupInsteadOfAnonymousFunctionDiagnosticAnalyzer' threw an exception of type 'System.NullReferenceException' with message 'Object reference not set to an instance of an object.'.	UwpMain		1	Compiler	Analyzer 'Roslynator.CSharp.DiagnosticAnalyzers.UseMethodGroupInsteadOfAnonymousFunctionDiagnosticAnalyzer' threw the following exception:
'Exception occurred with following context:
Compilation: UwpMobileBroadband
SyntaxTree: D:\src\trunk\Source\Uwp\Gui\UwpMain\Models\MainPageModel.cs
SyntaxNode: delegate { HtmlDocumentDialog.OpenHtmlDocumentDialog ... [AnonymousMethodExpressionSyntax]@[10279..10360) (354,4)-(357,5)

System.NullReferenceException: Object reference not set to an instance of an object.
   at Roslynator.CSharp.Refactorings.UseMethodGroupInsteadOfAnonymousFunctionRefactoring.AnalyzeAnonyousMethodExpression(SyntaxNodeAnalysisContext context)
   at Microsoft.CodeAnalysis.Diagnostics.AnalyzerExecutor.<>c__43`1.<ExecuteSyntaxNodeAction>b__43_0(ValueTuple`2 data)
   at Microsoft.CodeAnalysis.Diagnostics.AnalyzerExecutor.ExecuteAndCatchIfThrows_NoLock[TArg](DiagnosticAnalyzer analyzer, Action`1 analyze, TArg argument, Nullable`1 info)
-----
'.

Code:
		private void ExecuteSimpleShortcutFilePath(string filePath, string notUsed1, string notUsed)
		{
			Task.Run(
				delegate
				{
					HtmlDocumentDialog.OpenHtmlDocumentDialog(filePath);
				}
			);
		}

Please tell me, how I can help.
Regards
Ferdinand

**Comment by JosefPihrt** [comment] 2017-11-08 22:53
Duplicate of #190

**Closed** 2017-11-08 22:53 UTC
Labels: Area-Analyzers, Bug, Resolution-Duplicate
