### ISSUE TITLE
RCS1213 always triggers for private members, even if they are referenced

### ISSUE THREAD

**Issue by IanKemp** [JosefPihrt/Roslynator#239] opened 2017-12-28 12:16 UTC
RCS1213 (added in 1.6.10) seems to trigger for **any** member that is `private`, even if said member is referenced:

```csharp
IDictionary<Step, string> _urls; // triggers RCS1213 even though field is very obviously used!
public IDictionary<Step, string> Urls
{
    get { return _urls ?? new Dictionary<Step, string>(); }
    set { _urls = value; }
}
```

Changing the access to anything other than `private` causes RCS1213 to go away:

```csharp
protected IDictionary<Step, string> _urls; // no RCS1213 due to protected modifier
public IDictionary<Step, string> Urls
{
    get { return _urls ?? new Dictionary<Step, string>(); }
    set { _urls = value; }
}
```

**Comment by JosefPihrt** [comment] 2017-12-28 14:05
duplicate of #234

**Closed** 2017-12-28 14:05 UTC
Labels: Area-Analyzers, Bug, Resolution-Duplicate
