### ISSUE TITLE
Roslynator should be able to read rules from .editorconfig

### ISSUE THREAD

**Issue by lostmsu** [JosefPihrt/Roslynator#495] opened 2019-01-26 20:56 UTC
Problem is: it is inconvenient to create and attach rulesets to all new projects. It would be great, if I could set `roslynator_diagnostic = <severity>` anywhere in my Projects folder hierarchy.

**Comment by Danghor** [comment] 2019-07-31 10:36
I think this is a duplicate of #473

**Comment by felixhirt** [comment] 2019-12-05 08:50
I don't think its a duplicate. #473 is about making the warnings and refactoring consider formatting and variable name rules defined in editorconfig.

This issue is about using the analyzer severity rules in .editorconfig (like: "dotnet_diagnostic.RCS1020.severity = none"). 

At least thats how i interpret them.

I think this issue here can be closed, because this actually works. You can even use VisualStudio to add the rule to editorconfig (Tested in VisualStudio 16.4, with Roslynator Analyzers 2.1.0)

**Comment by Danghor** [comment] 2019-12-05 09:59
@felixhirt Makes sense. I also think the issue can be closed for the reasons you stated.

**Closed** 2019-12-12 18:34 UTC
Labels: Area-Analyzers, Resolution-Fixed

**Comment by lostmsu** [comment] 2019-12-12 19:36
@Danghor @felixhirt since this page might come up in search for "roslynator editorconfig", can you describe how to actually use the new feature?

**Comment by felixhirt** [comment] 2019-12-13 08:09
sure thing
In visual studio, you can go to the quick fixes (light bulb) on an analyzer result in code, and choose "configure or suppress issue" -> "configure XXX severity" to add the rule to editorconfig. I think you need to have an editorconfig file in advance, but you can generate one in visual studio as well (https://docs.microsoft.com/en-us/visualstudio/ide/create-portable-custom-editor-options?view=vs-2019)

**Comment by Danghor** [comment] 2019-12-16 00:36
For example, your `.editorconfig` file could contain the lines

```
dotnet_diagnostic.RCS1179.severity = none
dotnet_diagnostic.RS1020.severity = error
```

which would hide the RCS1179 diagnostic and fail the build for the RCS1020 diagnostic.

Currently, only the severity for Roslynator diagnostics can be configured in the `.editorconfig`. Other options, like if you prefer the ternary style or an if-else-block, cannot be configured yet.


Note: Visual Studio will adjust the severity in the `.editorconfig`, if you use the "Configure severity" option from Itelllisense in the code. If however, you configure the severity in the Solution Explorer under "Dependencies" -> "Analyzers", Visual Studio will create a `.ruleset` file instead, which might not be desired.

**Comment by marcospgp** [comment] 2021-07-27 09:03
Are there any updates to this? Can one configure Roslynator using `.editorconfig` yet? This would be very useful for VSCode with Omnisharp.

**Comment by felixhirt** [comment] 2021-07-27 10:17
I believe this issue was about VisualStudio, where it is supported. I think you should open a new issue to ask for VisualStudio Code support

**Comment by marcospgp** [comment] 2021-07-27 10:23
@felixhirt Setting the severity is supported, but other configuration is not, as mentioned above:

> Currently, only the severity for Roslynator diagnostics can be configured in the .editorconfig. Other options, like if you prefer the ternary style or an if-else-block, cannot be configured yet.

`.editorconfig` is editor agnostic for the most part, so I don't believe it makes a difference whether one is using Visual Studio or Visual Studio Code.

**Comment by felixhirt** [comment] 2021-07-27 10:39
@marcospgp Ah, i see. Indeed, as long as VisualStudio Code uses roslyn in the background, it should work the same way. I think you are looking for #473?
