### ISSUE TITLE
Exception in Visual Studio

### ISSUE THREAD

**Issue by MSeifert04** [JosefPihrt/Roslynator#403] opened 2018-07-04 17:16 UTC
I don't know what exactly triggered this exception but it was reported to me in Visual Studio:

```
System.NullReferenceException : Object reference not set to an instance of an object.
   at async Roslynator.CSharp.Refactorings.ImplementIEquatableOfTRefactoring.ComputeRefactoringAsync(<Unknown Parameters>)
   at async Roslynator.CSharp.Refactorings.ClassDeclarationRefactoring.ComputeRefactoringsAsync(<Unknown Parameters>)
   at async Roslynator.CSharp.Refactorings.MemberDeclarationRefactoring.ComputeRefactoringsAsync(<Unknown Parameters>)
   at async Roslynator.CSharp.Refactorings.RefactoringContext.ComputeRefactoringsForNodeAsync(<Unknown Parameters>)
   at async Roslynator.CSharp.Refactorings.RefactoringContext.ComputeRefactoringsAsync(<Unknown Parameters>)
   at async Roslynator.CSharp.Refactorings.RoslynatorCodeRefactoringProvider.ComputeRefactoringsAsync(<Unknown Parameters>)
   at async Microsoft.CodeAnalysis.CodeRefactorings.CodeRefactoringService.GetRefactoringFromProviderAsync(<Unknown Parameters>)
```

Let me know if I should provide further information :)

Roslynator 1.9.0
Visual Studio 2017 15.7.4

**Comment by JosefPihrt** [comment] 2018-07-04 17:42
duplicate of #394

**Closed** 2018-07-04 17:42 UTC
Labels: Area-Refactorings, Resolution-Duplicate

**Comment by MSeifert04** [comment] 2018-07-04 19:01
Oh, I haven't seen the duplicate. Thanks for pointing it out.

Would it be possible to make a new release soon? This error happens quite frequently.

**Comment by JosefPihrt** [comment] 2018-07-05 00:16
I will release new version soon (probably tomorrow).

**Comment by MSeifert04** [comment] 2018-07-05 04:54
Trank you

**Comment by JosefPihrt** [comment] 2018-07-05 14:10
Before release of new version you can get rid of this error by disabling the refactoring in the options.

Tools > Options > Roslynator > Refactorings > Uncheck "Implement IEquatable<T>"

**Comment by JosefPihrt** [comment] 2018-07-05 22:53
1.9.1 is out!
