### ISSUE TITLE
RCS1083 False Positive

### ISSUE THREAD

**Issue by nnpcYvIVl** [JosefPihrt/Roslynator#280] opened 2018-02-14 16:28 UTC
This code throws RCS1038. Isn't this a false positive?

```
using System.Collections.Generic;
using System.Linq;

namespace RCS1038_False_Positive
{
    public class TestClass
    {
        void TestMethod()
        {
            IEnumerable<string> fruits2 = new List<string> {"apple", "banana", "mango" };
            for (int i = 0; i < fruits2.Count(); i++)
                ;
        }
    }
}
```

```
Warning	RCS1083	Call 'Enumerable.Any' instead of 'Enumerable.Count'.
```

**Comment by JosefPihrt** [comment] 2018-02-14 17:21
duplicate of #200

**Comment by nnpcYvIVl** [comment] 2018-02-14 17:53
Thanks for the explanation. Perhaps the description of the analyzer should read ```Call 'Enumerable.Any' or 'Enumerable.Skip.Any' instead of 'Enumerable.Count'.``` to prevent confusion.

**Closed** 2018-03-01 23:28 UTC
Labels: Area-Analyzers, Resolution-Duplicate

**Comment by JosefPihrt** [comment] 2018-04-15 11:15
#315
