### ISSUE TITLE
Analyzer 'Roslynator.CSharp.DiagnosticAnalyzers.UseMethodGroupInsteadOfAnonymousFunctionDiagnosticAnalyzer' threw an exception of type 'System.NullReferenceException' with message 'Object reference not set to an instance of an object.'.

### ISSUE THREAD

**Issue by siewers** [JosefPihrt/Roslynator#271] opened 2018-02-07 13:55 UTC
I don't know what causes this, as there is nothing else than this in the output window:

`1>CSC : warning AD0001: Analyzer 'Roslynator.CSharp.DiagnosticAnalyzers.UseMethodGroupInsteadOfAnonymousFunctionDiagnosticAnalyzer' threw an exception of type 'System.NullReferenceException' with message 'Object reference not set to an instance of an object.'.
`

I saw that a couple of other bugs in the same analyzer was already fixed, but this error occurs in version 1.7.0 but not in 1.7.0-rc.

Is there a way to get more details about the exception?

**Comment by JosefPihrt** [comment] 2018-02-07 20:22
duplicate of #267

**Closed** 2018-02-07 20:22 UTC
Labels: Area-Analyzers, Bug, Resolution-Duplicate

**Comment by siewers** [comment] 2018-02-09 09:19
But that issue was closed. Where is this issue fixed? Is it released yet?

**Comment by JosefPihrt** [comment] 2018-02-09 10:28
The fix has not been released yet.
