### ISSUE TITLE
Bug: Roslynator.DotNet.Cli not using severity level from .editorconfig

### ISSUE THREAD

**Issue by shoter** [JosefPihrt/Roslynator#723] opened 2020-09-18 10:49 UTC
**Product and Version Used**: 
Roslynator.DotNet.Cli  manually compiled few days ago.

**Steps to Reproduce**:
1. Mark some code style rule as `info` in `.editorconfig`
2. use `roslynator fix` to fix your code with `--severity-level warning`
3. The rule will be fixed :(

My .editorconfig file:
```
[*Test?.cs]

dotnet_diagnostic.CA1707.severity = none
dotnet_diagnostic.CA1062.severity = none
dotnet_diagnostic.CA2234.severity = none


[**/Migrations/*.cs]
dotnet_diagnostic.CS1591.severity = none

[*.cs]
indent_size = 4
indent_style = space
tab_width = 4
end_of_line = crlf
insert_final_newline = false
dotnet_sort_system_directives_first = true
csharp_style_var_when_type_is_apparent = true:warning
csharp_using_directive_placement = inside_namespace:silent
dotnet_diagnostic.SA1101.severity = none
dotnet_diagnostic.SA1615.severity = suggestion
dotnet_diagnostic.CA1822.severity = none
dotnet_diagnostic.SA1633.severity = none
dotnet_diagnostic.SA1600.severity = none
dotnet_diagnostic.CS1591.severity = none
dotnet_diagnostic.SA1602.severity = none
dotnet_diagnostic.SA1100.severity = suggestion
dotnet_diagnostic.CA2007.severity = none
dotnet_diagnostic.SA1629.severity = none
dotnet_diagnostic.SA1405.severity = none
dotnet_diagnostic.SA1100.severity = suggestion
dotnet_diagnostic.SA1623.severity = none
dotnet_diagnostic.CA1062.severity = none
dotnet_naming_rule.static_must_be_pascal_case.severity = error
dotnet_naming_rule.static_must_be_pascal_case.symbols = static_const
dotnet_naming_rule.static_must_be_pascal_case.style = pascal_case
dotnet_diagnostic.SA1601.severity = none
dotnet_diagnostic.SA1405.severity = none
dotnet_diagnostic.CA1805.severity = suggestion
dotnet_diagnostic.CA1062.severity = none
```

**Expected Behavior**:
CLI should follow rules in .editorconfig

---

What I just checked is that when I give it severity `none` then it's not being fixed. Maybe there is problem with style priorities and not with .editorconfig?

**Comment by JosefPihrt** [comment] 2020-09-18 10:53
A duplicate of #676

**Closed** 2020-10-28 10:25 UTC
Labels: Area-CLI, Resolution-Duplicate
