### ISSUE TITLE
Error when running `dotnet build` when using Roslynator.Formatting.Analyzers package

### ISSUE THREAD

**Issue by tuananh-le** [JosefPihrt/Roslynator#837] opened 2021-08-05 14:38 UTC
**Product and Version Used**: 
Roslynator.Formatting.Analyzers v1.2.1

**Steps to Reproduce**:
- Install both Roslynator.Analyzers v3.2.0 and Roslynator.Formatting.Analyzers v1.2.1 in a .NET 5 project.
- Add`<TreatWarningsAsErrors>true</TreatWarningsAsErrors>` in Property Group in csproj file.
- Run `dotnet build`

**Actual Behavior**:
The following errors throw
```csharp
error AD0001: Analyzer 'Roslynator.Formatting.CSharp.AccessorListAnalyzer' threw an exception of type 'System.IO.FileLoadException' with message 'Could not load file or assembly 'Roslynator.Core, Version=2.1.0.3, Culture=neutral, PublicKeyToken=926ea54d246a765e'. Could not find or load a specific file. (0x80131621)'
error AD0001: Analyzer 'Roslynator.Formatting.CSharp.AddNewLineBeforeBinaryOperatorInsteadOfAfterItOrViceVersaAnalyzer' threw an exception of type 'System.IO.FileLoadException' with message 'Could not load file or assembly 'Roslynator.Common, Version=3.2.1.1, Culture=neutral, PublicKeyToken=926ea54d246a765e'. Could not find or load a specific file. (0x80131621)'
....
....
```

**Comment by tuananh-le** [comment] 2021-08-05 14:39
@JosefPihrt : Any ideas how to solve this issue? Thanks.

**Comment by JosefPihrt** [comment] 2021-08-05 15:06
A duplicate of #833

**Closed** 2021-08-05 15:07 UTC
Labels: Resolution-Duplicate, Area-Analyzers
