### ISSUE TITLE
RCS1058 - Use compound assignment. - Fix results in compile error when throwing exception

### ISSUE THREAD

**Issue by jasonchester** [JosefPihrt/Roslynator#800] opened 2021-05-05 13:00 UTC
**Product and Version Used**: 
vscode extension v3.2.0

**Steps to Reproduce**:

![image](https://user-images.githubusercontent.com/337720/117144756-4f225000-ad80-11eb-817f-7bdf583db389.png)

**Actual Behavior**:
given code
```csharp
newUser = newUser ?? throw new ArgumentNullException(nameof(newUser));
```

```json
{
	"owner": "csharp",
	"code": "RCS1058",
	"severity": 2,
	"message": "Use compound assignment. [WebApi]",
	"source": "csharp"
}
```

Suggest a fix to an invalid compond assignment
```csharp
newUser ??= throw new ArgumentNullException(nameof(newUser));
```

issue detail
```json
{
	"owner": "csharp",
	"code": "CS8115",
	"severity": 8,
	"message": "A throw expression is not allowed in this context. [WebApi]",
	"source": "csharp"
}
```

**Expected Behavior**
Fix to an invalid code state should not be offered.

**Comment by JosefPihrt** [comment] 2021-05-05 17:09
duplicate of #798

**Closed by JosefPihrt** 2021-05-05 17:09 UTC
