### ISSUE TITLE
Simplify code branching (RCS1218) breaks code

### ISSUE THREAD

**Issue by wanton7** [JosefPihrt/Roslynator#375] opened 2018-05-29 10:11 UTC
```csharp
if (configs.Count == 1)
{
}
else if (configs.Count > 1)
{
    throw new ConfigurationException($"Multiple collect config found for set {setKey}. User setkeyRequestTargets to give correct override.");
}
else
{
    var isMultiSelect = Adapter.IsMultiSelect(setKey);
    url = string.Format("~/Collect/" + (isMultiSelect ? "MultiSelect" : "Information") + "?p=Set-{0}&itemGuid=[itemGuid]", HttpUtility.UrlEncode(setKey));
}
```

Is converted to

```csharp
if (configs.Count != 1 && configs.Count > 1)
{
    throw new ConfigurationException($"Multiple collect config found for set {setKey}. User setkeyRequestTargets to give correct override.");
}
```

**Comment by wiz0u** [comment] 2018-05-29 10:59
Duplicate of #361

**Closed** 2018-05-29 11:01 UTC
