### ISSUE TITLE
Detect {standalone braced code} & suggest remove braces

### ISSUE THREAD

**Issue by wiz0u** [JosefPihrt/Roslynator#634] opened 2020-01-24 16:04 UTC
Roslynator could detect

	void someMethod()
	{
		...
		{
			standalone blocks of code
			that are not part of language construct
			like if,for,else,while,etc...
			but just indented into {braces}
		}
		...
	}

and offer "Remove braces" as a code fix

**Comment by JosefPihrt** [comment] 2020-01-30 11:08
This seems to be a duplicate of #44

**Comment by wiz0u** [comment] 2020-01-30 12:18
Hmm.. I see it is a complex issue.
But what is the current status of RCS1031?
It seems you deleted the analyzer, but can we still apply the code fix by manually selecting it as 'quick action' while the caret is on the opening/closing bracket ?
RCS1031 still appears in rulesets, I had it set to 'Hidden' but it does not seems to appear in contextual 'Quick actions' menus

**Comment by JosefPihrt** [comment] 2020-02-03 12:44
I deleted RCS1031 but then I revived it to remove braces from switch section.

before:
```cs
switch (x)
  case y:
    {
      return z;
    }
  default:
    return null;
```

after:
```cs
switch (x)
  case y:
    return z;
  default:
    return null;
```

**Closed** 2020-02-10 13:09 UTC
Labels: Area-Analyzers, Resolution-Duplicate
