### ISSUE TITLE
Refactor Request - Move Method to another class

### ISSUE THREAD

**Issue by ToolMaker** [JosefPihrt/Roslynator#408] opened 2018-07-06 12:37 UTC
Making changes to existing old legacy code without introducing bugs is a very important benefit that refactoring gives. Please can we add move a method out of its existing class into another

**Comment by JosefPihrt** [comment] 2018-07-06 16:29
duplicate of #221

**Comment by ToolMaker** [comment] 2018-07-08 19:05
thanks, indeed

**Closed** 2018-07-09 01:21 UTC
Labels: Area-Refactorings, Resolution-Duplicate
