### ISSUE TITLE
Crash in Convert to 'for' refactoring

### ISSUE THREAD

**Issue by tamlin-mike** [JosefPihrt/Roslynator#604] opened 2019-09-28 13:32 UTC
Roslynator 2.1.3 in VS2019 (16.2.5)

```
public void MethodName()
{
	//int max = 0;
	int i = 1;
	while (true)
	{
		if (i < max)
		{
		}
	}
}
```

Place cursor on "while" and select the Convert to 'for' refactoring. Crash in the preview pop-up window.
Uncomment definition of `max` and it works.

Stacktrace:
```
using MsCaCaCa=Microsoft.CodeAnalysis.CodeActions.CodeAction; // added for readability
System.InvalidOperationException : Sequence contains no elements
   at System.Linq.Enumerable.First[TSource](IEnumerable`1 source)
   at Roslynator.CSharp.Refactorings.ConvertWhileToForRefactoring.RefactorAsync(Document document,WhileStatementSyntax whileStatement,List`1 localDeclarations,CancellationToken cancellationToken)
   at async Roslynator.CSharp.Refactorings.ConvertWhileToForRefactoring.RefactorAsync(<Unknown Parameters>)
   at async MsCaCaCa.GetChangedSolutionAsync(<Unknown Parameters>)
   at async MsCaCaCa.ComputeOperationsAsync(<Unknown Parameters>)
   at async MsCaCaCa.GetPreviewOperationsAsync(<Unknown Parameters>)
   at async Microsoft.CodeAnalysis.Editor.Implementation.Suggestions.SuggestedAction.GetPreviewResultAsync(<Unknown Parameters>)
   at async Microsoft.CodeAnalysis.Editor.Implementation.Suggestions.SuggestedActionWithNestedFlavors.<>c__DisplayClass11_0.<GetPreviewAsync>b__0(<Unknown Parameters>)
   at async Microsoft.CodeAnalysis.Extensions.IExtensionManagerExtensions.PerformFunctionAsync[T](<Unknown Parameters>)```

**Comment by JosefPihrt** [comment] 2019-09-28 14:59
A duplicate of #586

**Closed by JosefPihrt** 2019-09-28 14:59 UTC
Labels: Area-Refactorings, Bug
