### ISSUE TITLE
Feature Request: analyzer and refactoring to rewrite "var foo = new Bar();" to "Bar foo = new();" (target-typed new expression)

### ISSUE THREAD

**Issue by IanKemp** [JosefPihrt/Roslynator#846] opened 2021-09-06 10:40 UTC
[C# 9.0 introduces target-typed `new` expressions.](https://docs.microsoft.com/en-us/dotnet/csharp/language-reference/proposals/csharp-9.0/target-typed-new) I find these easier and more intuitive to read than `var` expressions, hence I'm requesting an analyzer that would allow me to detect `var` expressions that are able to be written as target-typed `new` expressions, and a refactoring to actually perform that rewrite.

This analyzer should only trigger if the project langversion is C# 9.0 or higher.

**Comment by JosefPihrt** [comment] 2021-09-06 17:12
Duplicate of #786

work in progress: https://github.com/JosefPihrt/Roslynator/tree/analyzers/target-typed-new

**Closed** 2021-09-06 17:12 UTC
Labels: Resolution-Duplicate, Area-Analyzers
